USE [master]
GO

/****** Object:  Database [ProjectLife]    Script Date: 03/03/2017 15:08:30 ******/
CREATE DATABASE [ProjectLife]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjectLife', FILENAME = N'C:\Users\Celad-P033\ProjectLife.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProjectLife_log', FILENAME = N'C:\Users\Celad-P033\ProjectLife_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjectLife].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjectLife] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjectLife] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjectLife] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjectLife] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjectLife] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjectLife] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ProjectLife] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjectLife] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectLife] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjectLife] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjectLife] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjectLife] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjectLife] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjectLife] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjectLife] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ProjectLife] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjectLife] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjectLife] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjectLife] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjectLife] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjectLife] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ProjectLife] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjectLife] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProjectLife] SET  MULTI_USER 
GO

ALTER DATABASE [ProjectLife] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjectLife] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjectLife] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjectLife] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProjectLife] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProjectLife] SET QUERY_STORE = OFF
GO

USE [ProjectLife]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ProjectLife] SET  READ_WRITE 
GO


